//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.30 at 01:56:24 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.omn.com/com/omn/mpfactory/transport")
package com.omn.mpfactory.transport.user;
