package com.omn.mpfactory.model;
// Generated 31-Jan-2015 11:53:22 by Hibernate Tools 3.2.2.GA


import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.omn.mpfactory.util.model.AbstractEntity;

/**
 * AggloName generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="agglo_name")
public class AggloName  extends AbstractEntity {

     private State state;
     private String name;
     private List<AggloConnection> aggloConnections = new ArrayList<AggloConnection>(0);

    public AggloName() {
    }
	
    public AggloName(long id) {
        setId(id);
    }
    public AggloName(long id, State state, String name, List<AggloConnection> aggloConnections) {
       setId(id);
       this.state = state;
       this.name = name;
       this.aggloConnections = aggloConnections;
    }
   
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATE_ID")
    public State getState() {
        return this.state;
    }
    
    public void setState(State state) {
        this.state = state;
    }
    
    @Column(name="NAME", length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="aggloName")
    public List<AggloConnection> getAggloConnections() {
        return this.aggloConnections;
    }
    
    public void setAggloConnections(List<AggloConnection> aggloConnections) {
        this.aggloConnections = aggloConnections;
    }

}
