package com.omn.mpfactory.model;
// Generated 31-Jan-2015 11:53:22 by Hibernate Tools 3.2.2.GA


import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.omn.mpfactory.util.model.AbstractEntity;

/**
 * AggloConnection generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="agglo_connection")
public class AggloConnection extends AbstractEntity {


     private City city;
     private AggloName aggloName;

    public AggloConnection() {
    }

	
    public AggloConnection(long id) {
        setId(id);
    }
    public AggloConnection(long id, City city, AggloName aggloName) {
       setId(id);
       this.city = city;
       this.aggloName = aggloName;
    }
   
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CITY_ID")
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AGGLOM_ID")
    public AggloName getAggloName() {
        return this.aggloName;
    }
    
    public void setAggloName(AggloName aggloName) {
        this.aggloName = aggloName;
    }




}


