package com.omn.mpfactory.model;

// Generated 31-Jan-2015 11:53:22 by Hibernate Tools 3.2.2.GA

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.omn.mpfactory.util.model.AbstractEntity;

/**
 * City generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "city")
public class City extends AbstractEntity {

    private State state;
    private String name;
    private Long ord;
    private List<AggloConnection> aggloConnections = new ArrayList<AggloConnection>(0);
    private List<District> districts = new ArrayList<District>(0);

    public City() {
    }

    public City(long id, State state) {
        setId(id);
        this.state = state;
    }

    public City(long id, State state, String name, Long ord, List<AggloConnection> aggloConnections, List<District> districts) {
        setId(id);
        this.state = state;
        this.name = name;
        this.ord = ord;
        this.aggloConnections = aggloConnections;
        this.districts = districts;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STATE_ID", nullable = false)
    public State getState() {
        return this.state;
    }

    public void setState(State state) {
        this.state = state;
    }

    @Column(name = "NAME", length = 60)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "ORD")
    public Long getOrd() {
        return this.ord;
    }

    public void setOrd(Long ord) {
        this.ord = ord;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "city")
    public List<AggloConnection> getAggloConnections() {
        return this.aggloConnections;
    }

    public void setAggloConnections(List<AggloConnection> aggloConnections) {
        this.aggloConnections = aggloConnections;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "city")
    public List<District> getDistricts() {
        return this.districts;
    }

    public void setDistricts(List<District> districts) {
        this.districts = districts;
    }

}
