package com.omn.mpfactory.model;
// Generated 31-Jan-2015 11:53:22 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.omn.mpfactory.util.model.AbstractEntity;

/**
 * Company generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="company")
public class Company extends AbstractEntity {

     private String name;
     private String fullName;
     private String streetAndNr;
     private Long cityId;
     private Long districtId;
     private String mobile;
     private String phone;
     private String email;
     private String www;
     private Date ts;

    public Company() {
    }

	
    public Company(long id, Date ts) {
        setId(id);
        this.ts = ts;
    }
    public Company(long id, String name, String fullName, String streetAndNr, Long cityId, Long districtId, String mobile, String phone, String email, String www, Date ts) {
       setId(id);
       this.name = name;
       this.fullName = fullName;
       this.streetAndNr = streetAndNr;
       this.cityId = cityId;
       this.districtId = districtId;
       this.mobile = mobile;
       this.phone = phone;
       this.email = email;
       this.www = www;
       this.ts = ts;
    }
   

    @Column(name="NAME", length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="FULL_NAME", length=160)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    
    @Column(name="STREET_AND_NR", length=160)
    public String getStreetAndNr() {
        return this.streetAndNr;
    }
    
    public void setStreetAndNr(String streetAndNr) {
        this.streetAndNr = streetAndNr;
    }
    
    @Column(name="CITY_ID")
    public Long getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }
    
    @Column(name="DISTRICT_ID")
    public Long getDistrictId() {
        return this.districtId;
    }
    
    public void setDistrictId(Long districtId) {
        this.districtId = districtId;
    }
    
    @Column(name="MOBILE", length=20)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    
    @Column(name="PHONE", length=20)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    @Column(name="EMAIL", length=80)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="WWW", length=250)
    public String getWww() {
        return this.www;
    }
    
    public void setWww(String www) {
        this.www = www;
    }
    
    @Column(name="ts", nullable=false, length=19)
    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }




}


