package com.omn.mpfactory.model;
// Generated 31-Jan-2015 11:53:22 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.omn.mpfactory.util.model.AbstractEntity;

/**
 * District generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="district")
public class District extends AbstractEntity{

     private City city;
     private String name;

    public District() {
    }

	
    public District(long id, City city) {
        setId(id);
        this.city = city;
    }
    public District(long id, City city, String name) {
       setId(id);
       this.city = city;
       this.name = name;
    }
   
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CITY_ID", nullable=false)
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    
    @Column(name="NAME", length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

}


