package com.omn.mpfactory.model;

// Generated 31-Jan-2015 11:53:22 by Hibernate Tools 3.2.2.GA

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.omn.mpfactory.util.model.AbstractEntity;

/**
 * State generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "state")
public class State extends AbstractEntity {

    private String name;
    private List<AggloName> aggloNames = new ArrayList<AggloName>(0);
    private List<City> cities = new ArrayList<City>(0);

    public State() {
    }

    public State(long id) {
        setId(id);
    }

    public State(long id, String name, List<AggloName> aggloNames, List<City> cities) {
        setId(id);
        this.name = name;
        this.aggloNames = aggloNames;
        this.cities = cities;
    }

    @Column(name = "NAME", length = 60)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "state")
    public List<AggloName> getAggloNames() {
        return this.aggloNames;
    }

    public void setAggloNames(List<AggloName> aggloNames) {
        this.aggloNames = aggloNames;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "state")
    public List<City> getCities() {
        return this.cities;
    }

    public void setCities(List<City> cities) {
        this.cities = cities;
    }

}
