package com.omn.mpfactory.model;
// Generated 31-Jan-2015 11:53:22 by Hibernate Tools 3.2.2.GA


import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.omn.mpfactory.util.model.AbstractEntity;

/**
 * User generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="user_table")
public class User extends AbstractEntity{

     private String nick;
     private String email;
     private String passwordHash;
     private Long companyId;
     private String confirmationString;
     private List<UserRole> userRoles = new ArrayList<UserRole>(0);

    public User() {
    }
	
    public User(long id) {
        setId(id);
    }
    public User(long id, String nick, String email, String passwordHash, Long companyId, String confirmationString, List<UserRole> userRoles) {
       setId(id);
       this.nick = nick;
       this.email = email;
       this.passwordHash = passwordHash;
       this.companyId = companyId;
       this.confirmationString = confirmationString;
       this.userRoles = userRoles;
    }
   
    @Column(name="nick", length=100)
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    
    @Column(name="email", length=200)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="password_hash", length=160)
    public String getPasswordHash() {
        return this.passwordHash;
    }
    
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }
    
    @Column(name="COMPANY_ID")
    public Long getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }
    
    @Column(name="confirmation_string", length=250)
    public String getConfirmationString() {
        return this.confirmationString;
    }
    
    public void setConfirmationString(String confirmationString) {
        this.confirmationString = confirmationString;
    }
    
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="user")
    public List<UserRole> getUserRoles() {
        return this.userRoles;
    }
    
    public void setUserRoles(List<UserRole> userRoles) {
        this.userRoles = userRoles;
    }




}


